language: python
dist: trusty
sudo: required
os:
- linux
python:
- '2.7'
install:
- python --version
- pip --version
script:
- python setup.py install
after_success:
- python setup.py sdist
deploy:
  provider: pypi
  user: nnarain
  password:
    secure: MxIZKnRVceOLQcphV5o2rEsfEdm9eB7Ru1ky0EHedYVKKb/ZDXAdc3VY6P7C40iPoPHBrd/IspnKost9xPigqO4s6pCy9K7/5mnBVD57KlKyPaQBHWw5kfZYjoLcpMtrSvp3wsaPKoR1so5YZUmGUhvW7OKGExBcLA0GfD1EL4ZCJ0C3LmyBF3FScdiEXXeqNysKGt6GcW7xwBqshToYilROhnzmrjlAKaCxNtukUhLiwqLTTPN3KJ5iVJssssIL3Jh+viYIxJXno2/tswI12SWXc9VdPDxjLiBwxRd/c1X/GBrMIoUCRohoE9WOQ6DbK3LBm7lGKAHLKe8YFRMMT6j1EjUDeTzHS9aEbRTWJI8WP8mPSVeDZQl+eKnA+1Od20B1OzXwqMGhizrf0dd8mUchD94EwMLl371KoRyc8f3u+U4vpo0G3w9Te+Mr6d45ywTCbpCxlbKGqT2BUjkiUUbjPIDP8uJfJ8dHhWx8jheQVR9eUX7Abet3GWooLcrACH6Kii3UjZmJ8GB/DgmSwJqgjcLBiiLVGn9w98X03qTuUSKvCmWaGTJZtplZspn6ur6enu8zn4DnFOpKX3/PwuKkZAtPCqRRVC6b5mJ0TEp5E8pkHkJzDz92GKqDkqzSnIY7bAnDS5wAQUHu16peCwZOzWSStO6i4Fmxi6A5inU=
  distributions: sdist
  on:
    tags: true
